// PathMark: ./src/definitions/configs/airbnb-ts.ts
import { RULES } from "../../constants";
import type { Config } from ".";

export default {
  definitions: `{
    files: tsFiles,
    ${RULES}
  }`,
  ejected: true,
  enabled: true,
  id: "airbnb-ts",
  name: "AirBnb-Typescript",
  packages: [
    {
      declaredAs: "airbnbTypescript",
      package: "eslint-config-airbnb-typescript",
      requiresImport: false,
      subModule: "/lib/shared.js",
    },
  ],
  requiredPlugins: ["@typescript-eslint", "import", "react"],
  rules: `"@typescript-eslint/default-param-last": 2,
    "@typescript-eslint/dot-notation": [2, { allowKeywords: true }],
    "@typescript-eslint/naming-convention": [
      2,
      {
        format: ["camelCase", "PascalCase", "UPPER_CASE"],
        selector: "variable",
      },
      {
        format: ["camelCase", "PascalCase"],
        selector: "function",
      },
      {
        format: ["PascalCase"],
        selector: "typeLike",
      },
    ],
    "@typescript-eslint/no-array-constructor": 2,
    "@typescript-eslint/no-dupe-class-members": 2,
    "@typescript-eslint/no-empty-function": [
      2,
      {
        allow: ["arrowFunctions", "functions", "methods"],
      },
    ],
    "@typescript-eslint/no-extra-parens": [
      0,
      "all",
      {
        conditionalAssign: true,
        enforceForArrowConditionals: false,
        ignoreJSX: "all",
        nestedBinaryExpressions: false,
        returnAssign: false,
      },
    ],
    "@typescript-eslint/no-implied-eval": 2,
    "@typescript-eslint/no-loop-func": 2,
    "@typescript-eslint/no-loss-of-precision": 2,
    "@typescript-eslint/no-magic-numbers": [
      0,
      {
        detectObjects: false,
        enforceConst: true,
        ignore: [],
        ignoreArrayIndexes: true,
      },
    ],
    "@typescript-eslint/no-redeclare": 2,
    "@typescript-eslint/no-shadow": 2,
    "@typescript-eslint/no-unused-expressions": [
      2,
      {
        allowShortCircuit: false,
        allowTaggedTemplates: false,
        allowTernary: false,
      },
    ],
    "@typescript-eslint/no-unused-vars": [
      2,
      { args: "after-used", ignoreRestSiblings: true, vars: "all" },
    ],
    "@typescript-eslint/no-use-before-define": [
      2,
      { classes: true, functions: true, variables: true },
    ],
    "@typescript-eslint/no-useless-constructor": 2,
    "@typescript-eslint/require-await": 0,
    "@typescript-eslint/return-await": [2, "in-try-catch"],
    "brace-style": 0,
    camelcase: 0,
    "comma-dangle": 0,
    "comma-spacing": 0,
    "constructor-super": 0,
    "default-param-last": 0,
    "dot-notation": 0,
    "func-call-spacing": 0,
    "getter-return": 0,
    "import/extensions": [
      2,
      "ignorePackages",
      {
        js: "never",
        jsx: "never",
        mjs: "never",
        ts: "never",
        tsx: "never",
      },
    ],
    "import/named": 0,
    "import/no-extraneous-dependencies": [
      2,
      {
        devDependencies: [
          "test/**",
          "tests/**",
          "spec/**",
          "**/__tests__/**",
          "**/__mocks__/**",
          "test.{js,jsx}",
          "test.{ts,tsx}",
          "test-*.{js,jsx}",
          "test-*.{ts,tsx}",
          "**/*{.,_}{test,spec}.{js,jsx}",
          "**/*{.,_}{test,spec}.{ts,tsx}",
          "**/jest.config.js",
          "**/jest.config.ts",
          "**/jest.setup.js",
          "**/jest.setup.ts",
          "**/vue.config.js",
          "**/vue.config.ts",
          "**/webpack.config.js",
          "**/webpack.config.ts",
          "**/webpack.config.*.js",
          "**/webpack.config.*.ts",
          "**/rollup.config.js",
          "**/rollup.config.ts",
          "**/rollup.config.*.js",
          "**/rollup.config.*.ts",
          "**/gulpfile.js",
          "**/gulpfile.ts",
          "**/gulpfile.*.js",
          "**/gulpfile.*.ts",
          "**/Gruntfile{,.js}",
          "**/Gruntfile{,.ts}",
          "**/protractor.conf.js",
          "**/protractor.conf.ts",
          "**/protractor.conf.*.js",
          "**/protractor.conf.*.ts",
          "**/karma.conf.js",
          "**/karma.conf.ts",
          "**/.eslintrc.js",
          "**/.eslintrc.ts",
        ],
        optionalDependencies: false,
      },
    ],
    "import/no-named-as-default-member": 0,
    "import/no-unresolved": 0,
    indent: 0,
    "keyword-spacing": 0,
    "lines-between-class-members": 0,
    "no-array-constructor": 0,
    "no-const-assign": 0,
    "no-dupe-args": 0,
    "no-dupe-class-members": 0,
    "no-dupe-keys": 0,
    "no-empty-function": 0,
    "no-extra-parens": 0,
    "no-extra-semi": 0,
    "no-func-assign": 0,
    "no-implied-eval": 0,
    "no-import-assign": 0,
    "no-loop-func": 0,
    "no-loss-of-precision": 0,
    "no-magic-numbers": 0,
    "no-new-func": 0,
    "no-new-symbol": 0,
    "no-obj-calls": 0,
    "no-redeclare": 0,
    "no-return-await": 0,
    "no-setter-return": 0,
    "no-shadow": 0,
    "no-this-before-super": 0,
    "no-throw-literal": 0,
    "no-undef": 0,
    "no-unreachable": 0,
    "no-unsafe-negation": 0,
    "no-unused-expressions": 0,
    "no-unused-vars": 0,
    "no-use-before-define": 0,
    "no-useless-constructor": 0,
    "object-curly-spacing": 0,
    quotes: 0,
    "require-await": 0,
    semi: 0,
    "space-before-blocks": 0,
    "space-before-function-paren": 0,
    "space-infix-ops": 0,
    "valid-typeof": 0,`,
} satisfies Config;
// EOF
