// PathMark: ./src/definitions/configs/airbnb-base-variables.ts
import { RULES } from "../../constants";
import type { Config } from ".";

export default {
  definitions: `{
    files: jsFiles,
    ${RULES}
  }`,
  ejected: true,
  enabled: true,
  id: "airbnb-base",
  name: "AirBnb Base",
  nameSecondary: "Variables",
  packages: [
    {
      declaredAs: "airbnbBaseVariables",
      package: "eslint-config-airbnb-base",
      requiresImport: false,
      subModule: "/rules/variables",
    },
  ],
  requiredPlugins: [],
  rules: `"init-declarations": 0,
    "no-catch-shadow": 0,
    "no-delete-var": 2,
    "no-label-var": 2,
    "no-restricted-globals": [
      "error",
      {
        message:
          "Use Number.isFinite instead https://github.com/airbnb/javascript#standard-library--isfinite",
        name: "isFinite",
      },
      {
        message:
          "Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan",
        name: "isNaN",
      },
      ...[
        "addEventListener",
        "blur",
        "close",
        "closed",
        "confirm",
        "defaultStatus",
        "defaultstatus",
        "event",
        "external",
        "find",
        "focus",
        "frameElement",
        "frames",
        "history",
        "innerHeight",
        "innerWidth",
        "length",
        "location",
        "locationbar",
        "menubar",
        "moveBy",
        "moveTo",
        "name",
        "onblur",
        "onerror",
        "onfocus",
        "onload",
        "onresize",
        "onunload",
        "open",
        "opener",
        "opera",
        "outerHeight",
        "outerWidth",
        "pageXOffset",
        "pageYOffset",
        "parent",
        "print",
        "removeEventListener",
        "resizeBy",
        "resizeTo",
        "screen",
        "screenLeft",
        "screenTop",
        "screenX",
        "screenY",
        "scroll",
        "scrollbars",
        "scrollBy",
        "scrollTo",
        "scrollX",
        "scrollY",
        "self",
        "status",
        "statusbar",
        "stop",
        "toolbar",
        "top",
      ].map((g) => ({
        message: \`Use window.\${g} instead. https://github.com/facebook/create-react-app/blob/HEAD/packages/confusing-browser-globals/README.md\`,
        name: g,
      })),
    ],
    "no-shadow": 2,
    "no-shadow-restricted-names": 2,
    "no-undef": 2,
    "no-undef-init": 2,
    "no-undefined": 0,
    "no-unused-vars": [
      2,
      { args: "after-used", ignoreRestSiblings: true, vars: "all" },
    ],
    "no-use-before-define": [
      2,
      { classes: true, functions: true, variables: true },
    ],`,
} satisfies Config;
// EOF
