// PathMark: ./src/definitions/configs/airbnb-base-errors.ts
import { RULES } from "../../constants";
import type { Config } from ".";

export default {
  definitions: `{
    files: jsFiles,
    ${RULES}
  }`,
  ejected: true,
  enabled: true,
  id: "airbnb-base",
  name: "AirBnb Base",
  nameSecondary: "Errors",
  packages: [
    {
      declaredAs: "airbnbBaseErrors",
      package: "eslint-config-airbnb-base",
      requiresImport: false,
      subModule: "/rules/errors",
    },
  ],
  requiredPlugins: [],
  rules: `"for-direction": 2,
    "getter-return": [2, { allowImplicit: true }],
    "no-async-promise-executor": 2,
    "no-await-in-loop": 2,
    "no-compare-neg-zero": 2,
    "no-cond-assign": [2, "always"],
    "no-console": 1,
    "no-constant-binary-expression": 0,
    "no-constant-condition": 1,
    "no-control-regex": 2,
    "no-debugger": 2,
    "no-dupe-args": 2,
    "no-dupe-else-if": 2,
    "no-dupe-keys": 2,
    "no-duplicate-case": 2,
    "no-empty": 2,
    "no-empty-character-class": 2,
    "no-ex-assign": 2,
    "no-extra-boolean-cast": 2,
    "no-extra-parens": [
      0,
      "all",
      {
        conditionalAssign: true,
        enforceForArrowConditionals: false,
        ignoreJSX: "all",
        nestedBinaryExpressions: false,
        returnAssign: false,
      },
    ],
    "no-extra-semi": 2,
    "no-func-assign": 2,
    "no-import-assign": 2,
    "no-inner-declarations": 2,
    "no-invalid-regexp": 2,
    "no-irregular-whitespace": 2,
    "no-loss-of-precision": 2,
    "no-misleading-character-class": 2,
    "no-negated-in-lhs": 0,
    "no-new-native-nonconstructor": 0,
    "no-obj-calls": 2,
    "no-promise-executor-return": 2,
    "no-prototype-builtins": 2,
    "no-regex-spaces": 2,
    "no-setter-return": 2,
    "no-sparse-arrays": 2,
    "no-template-curly-in-string": 2,
    "no-unexpected-multiline": 2,
    "no-unreachable": 2,
    "no-unreachable-loop": [
      2,
      {
        ignore: [],
      },
    ],
    "no-unsafe-finally": 2,
    "no-unsafe-negation": 2,
    "no-unsafe-optional-chaining": [
      2,
      { disallowArithmeticOperators: true },
    ],
    "no-unused-private-class-members": 0,
    "no-useless-backreference": 2,
    "require-atomic-updates": 0,
    "use-isnan": 2,
    "valid-typeof": [2, { requireStringLiterals: true }],`,
} satisfies Config;
// EOF
