// PathMark: ./src/definitions/configs/id-groups.ts
export const testIds = [
  "jest",
  "cra/jest",
  "jest-dom",
  "jest-format",
  "no-only-test",
  "testing-library",
  "shopify/react-test",
];
export const reactIds = [
  "airbnb/react",
  "airbnb/react-hooks",
  "airbnb/react-a11y",
  "cra",
  "cra/jest",
  "cra/ts",
  "react",
  "react-hooks",
  "react-perf",
  "react-refresh",
  "rn",
  "rn-ip",
  "rn/ts",
  "rn/flowtype",
  "rn-p",
  "shopify/react-ts",
  "shopify/react",
  "shopify/react-test",
  "shopify/polaris",
  "standard-react",
  "standard-jsx",
  "storybook",
];
// EOF
