// PathMark: ./src/packages/rejected.ts

const rejected = new Set([
  // Maybe?
  "@tanstack/eslint-plugin-query",
  // if we get appropriate plugin functionality, heck yeah.
  "css-declaration-sorter",

  // Fork of import
  "eslint-plugin-i",

  // Irrelevant?
  "eslint-import-resolver-alias",
  "eslint-import-resolver-custom-alias",
  "eslint-plugin-local-rules",
  "eslint-plugin-local",
  "eslint-import-resolver-webpack",
  "eslint-import-resolver-babel-module",
  "eslint-import-resolver-jest",

  // Vue -- Hopefully to be added one day when its more popular than react!
  "@vue/eslint-config-airbnb",
  "@vue/eslint-config-prettier",
  "@vue/eslint-config-standard",
  "@vue/eslint-config-typescript",
  "eslint-plugin-nuxt",
  "eslint-plugin-prettier-vue",
  "eslint-plugin-vue-scoped-css",
  "eslint-plugin-vue",
  "eslint-plugin-vuejs-accessibility",
  "vue-eslint-parser",
  "@intlify/eslint-plugin-vue-i18n",
  "vue-i18n",
  "vue-cli-plugin-vuetify",

  // Vite
  "@vitejs/plugin-vue",
  "@vitejs/plugin-react",
  "vite-plugin-eslint",
  "@vitejs/plugin-basic-ssl",
  "vite-plugin-svgr",

  // Angular -- Hopefully to be added one day when its more popular than react!
  "@angular-eslint/eslint-plugin-template",
  "@angular-eslint/eslint-plugin",
  "@ngdaddy/eslint-config",
  "@ngdaddy/eslint-plugin",
  "@nrwl/angular",
  "@nx/angular",
  "eslint-plugin-angular",

  // Svelte -- Hopefully to be added one day when its more popular than react!
  "eslint-plugin-svelte",
  "eslint-plugin-svelte3",
  "svelte-eslint-parser",
  "prettier-plugin-svelte",

  // Ember -- Hopefully to be added one day when its more popular than react!
  "eslint-plugin-ember",

  // Broken / not-maintained / abandoned / scams / dead
  "eslint-plugin-babel",
  "eslint-plugin-deprecation",
  "eslint-plugin-graphql",
  "eslint-plugin-json",
  "eslint-plugin-lodash",
  "eslint-plugin-sort-keys-fix",
  "solhint",
  "@typescript-eslint/eslint-plugin-tslint",
  "tslint-config-prettier",
  "tslint-to-eslint-config",
  "tslint-etc",
  "prettier-plugin-solidity",

  // Plugin for linting plugins
  "eslint-plugin-eslint-plugin",

  // Typescript-eslint sub-modules
  "@typescript-eslint/experimental-utils",
  "@typescript-eslint/rule-tester",
  "@typescript-eslint/scope-manager",
  "@typescript-eslint/type-utils",
  "@typescript-eslint/types",
  "@typescript-eslint/typescript-estree",
  "@typescript-eslint/utils",
  "@typescript-eslint/visitor-keys",
  "typescript-eslint-language-service",

  // ES Lint submodules
  "@eslint-community/eslint-utils",
  "@eslint-community/regexpp",
  "@eslint/eslintrc",
  "eslint-compat-utils",
  "eslint-etc",
  "eslint-formatter-pretty",
  "eslint-import-resolver-node",
  "eslint-module-utils",
  "eslint-scope",
  "eslint-snapshot-test",
  "eslint-template-visitor",
  "eslint-visitor-keys",
  "eslint",
  "@nicolo-ribaudo/eslint-scope-5-internals",
  "estree-util-attach-comments",
  "estree-util-build-jsx",
  "@eslint-types/jsdoc",
  "@eslint-types/jsdoc",
  "@eslint-types/typescript-eslint",
  "@eslint-types/unicorn",
  "@types/eslint-scope",
  "@types/eslint",
  "@humanwhocodes/config-array",

  // Babel
  "@babel/eslint-parser",
  "estree-to-babel",
  "@babel/plugin-syntax-jsx",
  "@babel/plugin-transform-modules-commonjs",
  "@babel/plugin-syntax-typescript",
  "babel-plugin-polyfill-corejs3",
  "@babel/plugin-transform-parameters",
  "@babel/plugin-transform-classes",
  "@babel/plugin-transform-block-scoping",
  "babel-plugin-jest-hoist",
  "@babel/plugin-transform-destructuring",
  "@babel/plugin-transform-for-of",
  "@babel/plugin-transform-arrow-functions",
  "@babel/plugin-transform-spread",
  "@babel/plugin-transform-computed-properties",
  "@babel/plugin-transform-template-literals",
  "@babel/plugin-transform-shorthand-properties",
  "@babel/plugin-transform-literals",
  "@babel/plugin-transform-function-name",
  "@babel/plugin-transform-object-super",
  "@babel/plugin-transform-block-scoped-functions",
  "babel-plugin-istanbul",
  "@babel/plugin-transform-member-expression-literals",
  "@babel/plugin-transform-property-literals",
  "babel-plugin-polyfill-regenerator",
  "@babel/plugin-transform-async-to-generator",
  "@babel/plugin-transform-regenerator",
  "babel-plugin-polyfill-corejs2",
  "@babel/helper-plugin-utils",
  "@babel/plugin-transform-modules-systemjs",
  "@babel/plugin-transform-dotall-regex",
  "@babel/plugin-transform-unicode-regex",
  "@babel/plugin-transform-sticky-regex",
  "@babel/plugin-transform-modules-amd",
  "@babel/plugin-transform-exponentiation-operator",
  "@babel/plugin-transform-typeof-symbol",
  "@babel/plugin-transform-modules-umd",
  "@babel/plugin-transform-duplicate-keys",
  "@babel/plugin-transform-new-target",
  "@babel/plugin-transform-reserved-words",
  "@babel/plugin-transform-unicode-escapes",
  "@babel/plugin-transform-named-capturing-groups-regex",
  "@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining",
  "@babel/plugin-transform-typescript",
  "@babel/plugin-transform-react-jsx",
  "@babel/plugin-transform-runtime",
  "@babel/plugin-transform-react-display-name",
  "@babel/plugin-transform-optional-chaining",
  "@babel/plugin-transform-async-generator-functions",
  "@babel/plugin-transform-class-static-block",
  "@babel/plugin-transform-nullish-coalescing-operator",
  "@babel/plugin-transform-object-rest-spread",
  "@babel/plugin-transform-private-methods",
  "@babel/plugin-syntax-import-attributes",
  "@babel/plugin-transform-class-properties",
  "@babel/plugin-transform-private-property-in-object",
  "@babel/plugin-transform-export-namespace-from",
  "@babel/plugin-transform-numeric-separator",
  "@babel/plugin-transform-logical-assignment-operators",
  "@babel/plugin-transform-optional-catch-binding",
  "@babel/plugin-transform-json-strings",
  "@babel/plugin-transform-unicode-property-regex",
  "@babel/plugin-bugfix-safari-id-destructuring-collision-in-function-expression",
  "@babel/plugin-syntax-import-assertions",
  "@babel/plugin-syntax-import-assertions",
  "@babel/plugin-transform-unicode-sets-regex",
  "@babel/preset-react",
  "@babel/plugin-transform-flow-strip-types",
  "@babel/plugin-syntax-flow",
  "@babel/plugin-proposal-decorators",
  "@babel/plugin-syntax-decorators",
  "@babel/plugin-transform-react-jsx-source",
  "@babel/plugin-transform-react-jsx-self",
  "babel-plugin-dynamic-import-node",
  "babel-plugin-styled-components",
  "@babel/plugin-transform-react-constant-elements",
  "babel-plugin-react-native-web",
  "babel-plugin-inline-react-svg",
  "babel-plugin-react-require",
  "find-babel-config",
  "@svgr/babel-plugin-add-jsx-attribute",
  "babel-plugin-module-resolver",

  // Webpack
  "eslint-webpack-plugin",
  "fork-ts-checker-webpack-plugin",
  "terser-webpack-plugin",
  "html-webpack-plugin",
  "webpack-merge",
  "copy-webpack-plugin",
  "@webpack-cli/configtest",
  "tsconfig-paths-webpack-plugin",
  "optimize-css-assets-webpack-plugin",
  "@sentry/webpack-plugin",
  "css-minimizer-webpack-plugin",
  "pnp-webpack-plugin",
  "compression-webpack-plugin",
  "node-polyfill-webpack-plugin",

  // Various / Out of scope
  "@axe-core/react",
  "@biomejs/biome",
  "@codemirror/lint",
  "@es-joy/jsdoccomment",
  "@html-validate/stylish",
  "@ianvs/eslint-stats",
  "@ls-lint/ls-lint",
  "@mapbox/jsonlint-lines-primitives",
  "@mdx-js/esbuild",
  "@redocly/cli",
  "@redocly/openapi-core",
  "@rushstack/eslint-patch",
  "@types/lint-staged",
  "conventional-changelog-eslint",
  "cspell",
  "doiuse",
  "ember-template-lint",
  "eslint-define-config",
  "eslint-formatter-gitlab",
  "eslint-plugin-diff",
  "eslint-watch",
  "flowbite",
  "gherkin-lint",
  "gulp-eslint",
  "hast-util-to-mdast",
  "html-validate",
  "ignore",
  "jest-runner-eslint",
  "jest-config",
  "json-fixer",
  "jsx-ast-utils",
  "knip",
  "lint-staged",
  "lockfile-lint-api",
  "oxlint",
  "parse-function",
  "standard-engine",
  "standard",
  "unified-lint-rule",
  "unist-util-find",
  "unist-util-visit",
  "xo",
  "cosmiconfig",
  "lilconfig",
  "strip-json-comments",
  "write-file-atomic",
  "dotenv",
  "update-browserslist-db",
  "define-data-property",
  "enhanced-resolve",
  "loose-envify",
  "defaults",
  "rc",
  "ua-parser-js",
  "strnum",
  "registry-auth-token",
  "bonjour-service",
  "@svgr/plugin-jsx",
  "process-warning",
  "styled-jsx",
  "unplugin",
  "markdown-to-jsx",
  "redeyed",
  "react-scripts",
  "graphql-config",
  "@pnpm/npm-conf",
  "@pnpm/config.env-replace",
  "xss",
  "karma-chrome-launcher",
  "papaparse",
  "swiper",
  "lottie-web",
  "react-property",
  "@nestjs/config",
  "@tailwindcss/typography",
  "config",
  "@serverless/dashboard-plugin",
  "@salesforce/plugin-apex",
  "@release-it/conventional-changelog",
  "pretty-quick",
  "@jimp/plugin-resize",
  "application-config-path",
  "requirejs-config-file",
  "nconf",
  "m3u8-parser",
  "@percy/config",
  "mpd-parser",
  "puppeteer-extra-plugin",
  "release-it",
  "puppeteer-extra-plugin-stealth",
  "@parcel/config-default",
  "videojs-contrib-quality-levels",
  "prettysize",
  "snyk-config",
  "find-config",
  "@verdaccio/config",
  "plugin",
  "mongoose-paginate-v2",
  "@transloadit/prettier-bytes",
  "xml-but-prettier",
  "prettier-bytes",
  "tailwindcss-radix",
  "@azure/app-configuration",
  "@luminati-io/luminati-proxy",
  "fined",
  "vscode-langservers-extracted",

  // Fastify
  "fastify-plugin",
  "@fastify/error",
  "@fastify/static",
  "@fastify/cookie",
  "@fastify/autoload",
  "fastify-openapi-glue",
  "@fastify/basic-auth",
  "@fastify/multipart",
  "@fastify/view",

  // OCLIF
  "@oclif/plugin-help",
  "@oclif/plugin-not-found",
  "@oclif/plugin-warn-if-update-available",
  "@oclif/plugin-plugins",
  "@oclif/plugin-autocomplete",

  // Firebase
  "firebase",
  "@firebase/remote-config",
  "@firebase/remote-config-compat",
  "@react-native-firebase/remote-config",

  // JSS
  "jss-plugin-global",
  "jss-plugin-nested",
  "jss-plugin-camel-case",
  "jss-plugin-default-unit",
  "jss-plugin-vendor-prefixer",
  "jss-plugin-props-sort",

  // Rollup
  "@rollup/pluginutils",
  "@rollup/plugin-babel",
  "@rollup/plugin-node-resolve",
  "@rollup/plugin-replace",
  "@rollup/plugin-babel",
  "@rollup/plugin-json",
  "rollup-plugin-visualizer",
  "@rollup/plugin-typescript",
  "rollup-plugin-dts",
  "@rollup/plugin-commonjs",

  // Smithy
  "@smithy/node-config-provider",
  "@smithy/config-resolver",
  "@smithy/util-config-provider",
  "@smithy/eventstream-serde-config-resolver",

  // Octokit
  "@octokit/plugin-paginate-rest",
  "@octokit/plugin-rest-endpoint-methods",
  "@octokit/plugin-retry",
  "@octokit/plugin-throttling",

  // CSS / Postcss
  "postcss",
  "autoprefixer",
  "postcss-modules-local-by-default",
  "postcss-modules-scope",
  "postcss-load-config",
  "mini-css-extract-plugin",
  "postcss-import",
  "postcss-calc",
  "postcss-minify-params",
  "postcss-preset-env",
  "postcss-pxtorem",
  "cssnano",
  "postcss-modules-extract-imports",

  // aws
  "@aws-sdk/credential-provider-ini",
  "@aws-sdk/credential-provider-process",
  "@aws-sdk/region-config-resolver",

  // npm-package-json
  "@wordpress/npm-package-json-lint-config",
  "npm-package-json-lint-config-default",
  "npm-package-json-lint",

  // Remark / MDX / Unified / Markdown stuff
  "@astrojs/markdown-remark",
  "@mapbox/hast-util-table-cell-style",
  "@mdx-js/loader",
  "@mdx-js/mdx",
  "@mdx-js/react",
  "@theguild/remark-npm2yarn",
  "commonmark",
  "gatsby-transformer-remark",
  "markdown-escapes",
  "markdown-it-attrs",
  "markdown-it",
  "markdown-toc",
  "mdast-add-list-metadata",
  "micromark-core-commonmark",
  "micromark",
  "react-markdown",
  "react-native-markdown-display",
  "rehype-katex",
  "rehype-raw",
  "remark-breaks",
  "remark-cli",
  "remark-directive",
  "remark-emoji",
  "remark-external-links",
  "remark-footnotes",
  "remark-frontmatter",
  "remark-gfm",
  "remark-github",
  "remark-html",
  "remark-lint-blockquote-indentation",
  "remark-lint-checkbox-character-style",
  "remark-lint-code-block-style",
  "remark-lint-definition-case",
  "remark-lint-definition-spacing",
  "remark-lint-emphasis-marker",
  "remark-lint-fenced-code-flag",
  "remark-lint-fenced-code-marker",
  "remark-lint-file-extension",
  "remark-lint-final-definition",
  "remark-lint-final-newline",
  "remark-lint-hard-break-spaces",
  "remark-lint-heading-increment",
  "remark-lint-heading-style",
  "remark-lint-link-title-style",
  "remark-lint-list-item-bullet-indent",
  "remark-lint-list-item-content-indent",
  "remark-lint-list-item-indent",
  "remark-lint-list-item-spacing",
  "remark-lint-maximum-heading-length",
  "remark-lint-maximum-line-length",
  "remark-lint-no-auto-link-without-protocol",
  "remark-lint-no-blockquote-without-marker",
  "remark-lint-no-consecutive-blank-lines",
  "remark-lint-no-duplicate-definitions",
  "remark-lint-no-duplicate-headings",
  "remark-lint-no-emphasis-as-heading",
  "remark-lint-no-file-name-articles",
  "remark-lint-no-file-name-consecutive-dashes",
  "remark-lint-no-file-name-irregular-characters",
  "remark-lint-no-file-name-mixed-case",
  "remark-lint-no-file-name-outer-dashes",
  "remark-lint-no-heading-content-indent",
  "remark-lint-no-heading-punctuation",
  "remark-lint-no-inline-padding",
  "remark-lint-no-literal-urls",
  "remark-lint-no-multiple-toplevel-headings",
  "remark-lint-no-shell-dollars",
  "remark-lint-no-shortcut-reference-image",
  "remark-lint-no-shortcut-reference-link",
  "remark-lint-no-table-indentation",
  "remark-lint-no-undefined-references",
  "remark-lint-no-unused-definitions",
  "remark-lint-ordered-list-marker-style",
  "remark-lint-ordered-list-marker-value",
  "remark-lint-rule-style",
  "remark-lint-strong-marker",
  "remark-lint-table-cell-padding",
  "remark-lint-table-pipe-alignment",
  "remark-lint-table-pipes",
  "remark-lint-unordered-list-marker-style",
  "remark-math",
  "remark-mdx-frontmatter",
  "remark-mdx",
  "remark-message-control",
  "remark-parse",
  "remark-preset-lint-consistent",
  "remark-preset-lint-markdown-style-guide",
  "remark-reference-links",
  "remark-rehype",
  "remark-retext",
  "remark-slug",
  "remark-smartypants",
  "remark-squeeze-paragraphs",
  "remark-stringify",
  "remark-toc",
  "remark-validate-links",
  "remark",
  "remarkable",
  "strip-markdown",
  "unified",
  "vfile",

  // Markdownlint is poorly supported for integration with ESLint
  "markdownlint-cli",
  "markdownlint-cli2",
  "markdownlint",

  // Sarif
  "node-sarif-builder",
  "@microsoft/eslint-formatter-sarif",

  // Stylistic
  "@stylistic/eslint-plugin-js",
  "@stylistic/eslint-plugin-jsx",
  "@stylistic/eslint-plugin-plus",
  "@stylistic/eslint-plugin-ts",

  // Prettier Stuffs
  "prettier",
  "@types/eslint-config-prettier",
  "@types/eslint-plugin-prettier",
  "prettier-eslint-cli",
  "prettier-eslint",
  "prettier-linter-helpers",

  // Automatically included
  "globals",

  // Stylelint
  "@gitlab/stylelint-config",
  "nx-stylelint",
  "stylelint-config-prettier-scss",
  "stylelint-config-prettier",
  "stylelint-config-sass-guidelines",
  "stylelint-config-twbs-bootstrap",
  "stylelint-declaration-block-no-ignored-properties",
  "stylelint-declaration-strict-value",
  "stylelint-order",
  "stylelint-processor-styled-components",
  "stylelint-scss",
  "stylelint-webpack-plugin",
  "stylelint",
  "stylelint-prettier",
  "stylelint-config-recommended",
  "stylelint-config-standard",
  "stylelint-config-recommended-scss",
  "stylelint-config-standard-scss",
  "stylelint-config-css-modules",
  "stylelint-config-recess-order",
  "stylelint-config-idiomatic-order",

  // Commitlint
  "@commitlint/cli",
  "@commitlint/ensure",
  "@commitlint/execute-rule",
  "@commitlint/is-ignored",
  "@commitlint/lint",
  "@commitlint/message",
  "@commitlint/parse",
  "@commitlint/resolve-extends",
  "@commitlint/rules",
  "@commitlint/to-lines",
  "@commitlint/top-level",
  "commitlint",
  "@commitlint/config-validator",
  "@commitlint/config-conventional",

  // Monorepo stuffs
  "@backstage/eslint-plugin",
  "@backstage/config",
  "@nrwl/eslint-plugin-nx",
  "@nrwl/linter",
  "@nx/eslint-plugin",
  "@nx/eslint",
  "@nx/linter",
  "@nx/next",
  "@rushstack/eslint-plugin-security",
  "@rushstack/eslint-plugin",
  "syncpack",
]);

export default rejected;
// EOF
