// PathMark: ./src/packages/rejected.ts

const rejected = new Set([
  // Maybe?
  "@tanstack/eslint-plugin-query",

  // Fork of import
  "eslint-plugin-i",

  // Irrelevant?
  "eslint-import-resolver-alias",
  "eslint-import-resolver-custom-alias",
  "eslint-plugin-local-rules",
  "eslint-plugin-local",
  "eslint-import-resolver-webpack",
  "eslint-import-resolver-babel-module",
  "eslint-import-resolver-jest",

  // Vue -- Hopefully to be added one day when its more popular than react!
  "@vue/eslint-config-airbnb",
  "@vue/eslint-config-prettier",
  "@vue/eslint-config-standard",
  "@vue/eslint-config-typescript",
  "eslint-plugin-nuxt",
  "eslint-plugin-prettier-vue",
  "eslint-plugin-vue-scoped-css",
  "eslint-plugin-vue",
  "eslint-plugin-vuejs-accessibility",
  "vue-eslint-parser",
  "@intlify/eslint-plugin-vue-i18n",

  // Angular -- Hopefully to be added one day when its more popular than react!
  "@angular-eslint/eslint-plugin-template",
  "@angular-eslint/eslint-plugin",
  "@ngdaddy/eslint-config",
  "@ngdaddy/eslint-plugin",
  "@nrwl/angular",
  "@nx/angular",
  "eslint-plugin-angular",

  // Svelte -- Hopefully to be added one day when its more popular than react!
  "eslint-plugin-svelte",
  "eslint-plugin-svelte3",
  "svelte-eslint-parser",

  // Ember -- Hopefully to be added one day when its more popular than react!
  "eslint-plugin-ember",

  // Broken / not-maintained / abandoned / scams
  "eslint-plugin-babel",
  "eslint-plugin-deprecation",
  "eslint-plugin-graphql",
  "eslint-plugin-json",
  "eslint-plugin-lodash",
  "eslint-plugin-sort-keys-fix",
  "solhint",

  // Plugin for linting plugins
  "eslint-plugin-eslint-plugin",

  // Typescript-eslint sub-modules
  "@typescript-eslint/experimental-utils",
  "@typescript-eslint/rule-tester",
  "@typescript-eslint/scope-manager",
  "@typescript-eslint/type-utils",
  "@typescript-eslint/types",
  "@typescript-eslint/typescript-estree",
  "@typescript-eslint/utils",
  "@typescript-eslint/visitor-keys",
  "typescript-eslint-language-service",

  // Tslint is a dead project, replaced by @typescript-eslint
  "@typescript-eslint/eslint-plugin-tslint",
  "tslint-config-prettier",
  "tslint-to-eslint-config",

  // ES Lint submodules
  "@eslint-community/eslint-utils",
  "@eslint-community/regexpp",
  "@eslint/eslintrc",
  "eslint-compat-utils",
  "eslint-etc",
  "eslint-formatter-pretty",
  "eslint-import-resolver-node",
  "eslint-module-utils",
  "eslint-scope",
  "eslint-snapshot-test",
  "eslint-template-visitor",
  "eslint-visitor-keys",
  "eslint",
  "@nicolo-ribaudo/eslint-scope-5-internals",
  "estree-util-attach-comments",
  "estree-util-build-jsx",

  // Various / Out of scope
  "@axe-core/react",
  "@babel/eslint-parser",
  "estree-to-babel",
  "@biomejs/biome",
  "@codemirror/lint",
  "@ianvs/eslint-stats",
  "@ls-lint/ls-lint",
  "@mapbox/jsonlint-lines-primitives",
  "@mdx-js/esbuild",
  "@redocly/cli",
  "@redocly/openapi-core",
  "@rushstack/eslint-patch",
  "@types/lint-staged",
  "conventional-changelog-eslint",
  "cspell",
  "doiuse",
  "ember-template-lint",
  "eslint-define-config",
  "eslint-formatter-gitlab",
  "eslint-plugin-diff",
  "eslint-watch",
  "eslint-webpack-plugin",
  "flowbite",
  "fork-ts-checker-webpack-plugin",
  "gherkin-lint",
  "gulp-eslint",
  "hast-util-to-mdast",
  "html-validate",
  "ignore",
  "json-fixer",
  "jsx-ast-utils",
  "knip",
  "lint-staged",
  "lockfile-lint-api",
  "oxlint",
  "standard-engine",
  "standard",
  "unified-lint-rule",
  "unist-util-find",
  "unist-util-visit",
  "xo",
  "@es-joy/jsdoccomment",
  "parse-function",
  "jest-runner-eslint",
  "@html-validate/stylish",

  // npm-package-json
  "@wordpress/npm-package-json-lint-config",
  "npm-package-json-lint-config-default",
  "npm-package-json-lint",

  // Remark / MDX / Unified / Markdown stuff
  "@astrojs/markdown-remark",
  "@mapbox/hast-util-table-cell-style",
  "@mdx-js/loader",
  "@mdx-js/mdx",
  "@mdx-js/react",
  "@theguild/remark-npm2yarn",
  "commonmark",
  "gatsby-transformer-remark",
  "markdown-escapes",
  "markdown-it-attrs",
  "markdown-it",
  "markdown-toc",
  "mdast-add-list-metadata",
  "micromark-core-commonmark",
  "micromark",
  "react-markdown",
  "react-native-markdown-display",
  "rehype-katex",
  "remark-breaks",
  "remark-cli",
  "remark-directive",
  "remark-emoji",
  "remark-external-links",
  "remark-footnotes",
  "remark-frontmatter",
  "remark-gfm",
  "remark-github",
  "remark-html",
  "remark-lint-blockquote-indentation",
  "remark-lint-checkbox-character-style",
  "remark-lint-code-block-style",
  "remark-lint-definition-case",
  "remark-lint-definition-spacing",
  "remark-lint-emphasis-marker",
  "remark-lint-fenced-code-flag",
  "remark-lint-fenced-code-marker",
  "remark-lint-file-extension",
  "remark-lint-final-definition",
  "remark-lint-final-newline",
  "remark-lint-hard-break-spaces",
  "remark-lint-heading-increment",
  "remark-lint-heading-style",
  "remark-lint-link-title-style",
  "remark-lint-list-item-bullet-indent",
  "remark-lint-list-item-content-indent",
  "remark-lint-list-item-indent",
  "remark-lint-list-item-spacing",
  "remark-lint-maximum-heading-length",
  "remark-lint-maximum-line-length",
  "remark-lint-no-auto-link-without-protocol",
  "remark-lint-no-blockquote-without-marker",
  "remark-lint-no-consecutive-blank-lines",
  "remark-lint-no-duplicate-definitions",
  "remark-lint-no-duplicate-headings",
  "remark-lint-no-emphasis-as-heading",
  "remark-lint-no-file-name-articles",
  "remark-lint-no-file-name-consecutive-dashes",
  "remark-lint-no-file-name-irregular-characters",
  "remark-lint-no-file-name-mixed-case",
  "remark-lint-no-file-name-outer-dashes",
  "remark-lint-no-heading-content-indent",
  "remark-lint-no-heading-punctuation",
  "remark-lint-no-inline-padding",
  "remark-lint-no-literal-urls",
  "remark-lint-no-multiple-toplevel-headings",
  "remark-lint-no-shell-dollars",
  "remark-lint-no-shortcut-reference-image",
  "remark-lint-no-shortcut-reference-link",
  "remark-lint-no-table-indentation",
  "remark-lint-no-undefined-references",
  "remark-lint-no-unused-definitions",
  "remark-lint-ordered-list-marker-style",
  "remark-lint-ordered-list-marker-value",
  "remark-lint-rule-style",
  "remark-lint-strong-marker",
  "remark-lint-table-cell-padding",
  "remark-lint-table-pipe-alignment",
  "remark-lint-table-pipes",
  "remark-lint-unordered-list-marker-style",
  "remark-math",
  "remark-mdx-frontmatter",
  "remark-mdx",
  "remark-message-control",
  "remark-parse",
  "remark-preset-lint-consistent",
  "remark-preset-lint-markdown-style-guide",
  "remark-reference-links",
  "remark-rehype",
  "remark-retext",
  "remark-slug",
  "remark-smartypants",
  "remark-squeeze-paragraphs",
  "remark-stringify",
  "remark-toc",
  "remark-validate-links",
  "remark",
  "remarkable",
  "strip-markdown",
  "unified",
  "vfile",

  // Markdownlint is poorly supported for integration with ESLint
  "markdownlint-cli",
  "markdownlint-cli2",
  "markdownlint",

  // Sarif
  "node-sarif-builder",
  "@microsoft/eslint-formatter-sarif",

  // Stylistic
  "@stylistic/eslint-plugin-ts",
  "@stylistic/eslint-plugin-jsx",
  "@stylistic/eslint-plugin-js",
  "@stylistic/eslint-plugin-plus",

  // Prettier Stuffs
  "@types/eslint-config-prettier",
  "@types/eslint-plugin-prettier",
  "prettier-eslint-cli",
  "prettier-eslint",
  "prettier-linter-helpers",
  "vite-plugin-eslint",

  // ES Lint types
  "@eslint-types/jsdoc",
  "@eslint-types/jsdoc",
  "@eslint-types/typescript-eslint",
  "@eslint-types/unicorn",
  "@types/eslint-scope",
  "@types/eslint",

  // Automatically included
  "globals",

  // Stylelint
  "@gitlab/stylelint-config",
  "nx-stylelint",
  "stylelint-config-prettier-scss",
  "stylelint-config-prettier",
  "stylelint-config-sass-guidelines",
  "stylelint-config-twbs-bootstrap",
  "stylelint-declaration-block-no-ignored-properties",
  "stylelint-declaration-strict-value",
  "stylelint-order",
  "stylelint-processor-styled-components",
  "stylelint-scss",
  "stylelint-webpack-plugin",
  "stylelint",

  // Commitlint
  "@commitlint/cli",
  "@commitlint/ensure",
  "@commitlint/execute-rule",
  "@commitlint/is-ignored",
  "@commitlint/lint",
  "@commitlint/message",
  "@commitlint/parse",
  "@commitlint/resolve-extends",
  "@commitlint/rules",
  "@commitlint/to-lines",
  "@commitlint/top-level",
  "commitlint",

  // Monorepo stuffs
  "@backstage/eslint-plugin",
  "@nrwl/eslint-plugin-nx",
  "@nrwl/linter",
  "@nx/eslint-plugin",
  "@nx/eslint",
  "@nx/linter",
  "@nx/next",
  "@rushstack/eslint-plugin-security",
  "@rushstack/eslint-plugin",
  "eslint-config-turbo",
  "syncpack",
]);

export default rejected;
// EOF
