// PathMark: ./src/conflicts/incompatibilities.ts

/*
  This file is fully generated, to edit it change ./get-incompatibilities.ts
  Generated on 5/15/2024
*/

import { type ConflictCache } from "./types";

const incompatibles: ConflictCache = {
  "airbnb-base-best-practices": {
    "prettier/prettier": 0,
  },
  "airbnb-base-es6": {
    "@stylistic/arrow-parens": 0,
  },
  "airbnb-base-style": {
    "@babel/object-curly-spacing": 0,
    "@stylistic/quote-props": 0,
    "@stylistic/semi": 0,
    "prettier/prettier": 0,
  },
  "airbnb-ts": {
    "@stylistic/semi": 0,
    "prettier/prettier": 0,
    "prettier-tailwind/prettier": 0,
  },
  google: {
    "@stylistic/arrow-parens": 0,
    "@stylistic/block-spacing": 0,
    "@stylistic/brace-style": 0,
    "@stylistic/indent": 0,
    "@stylistic/object-curly-spacing": 0,
    "@stylistic/operator-linebreak": 0,
    "@stylistic/semi": 0,
    "jsdoc/check-tag-names": 0,
    "prettier/prettier": 0,
  },
  "import-sort": {
    "perfectionist/sort-imports": 0,
    "perfectionist/sort-named-imports": 0,
  },
  jsdoc: {
    "valid-jsdoc": 0,
  },
  perfectionist: {
    "simple-import-sort/imports": 0,
    "sort-class-members/sort-class-members": 0,
  },
  prettier: {
    "@stylistic/arrow-parens": 0,
    "@stylistic/brace-style": 0,
    "@stylistic/indent": 0,
    "@stylistic/indent-binary-ops": 0,
    "@stylistic/jsx-indent": 0,
    "@stylistic/jsx-one-expression-per-line": 0,
    "@stylistic/member-delimiter-style": 0,
    "@stylistic/multiline-ternary": 0,
    "@stylistic/operator-linebreak": 0,
    "@stylistic/quote-props": 0,
    "@stylistic/quotes": 0,
    "@stylistic/semi": 0,
    "@stylistic/yield-star-spacing": 0,
  },
  "prettier-plugin": {
    "@stylistic/arrow-parens": 0,
    "@stylistic/brace-style": 0,
    "@stylistic/indent": 0,
    "@stylistic/indent-binary-ops": 0,
    "@stylistic/jsx-indent": 0,
    "@stylistic/jsx-one-expression-per-line": 0,
    "@stylistic/member-delimiter-style": 0,
    "@stylistic/multiline-ternary": 0,
    "@stylistic/operator-linebreak": 0,
    "@stylistic/quote-props": 0,
    "@stylistic/quotes": 0,
    "@stylistic/semi": 0,
    "@stylistic/yield-star-spacing": 0,
    "@typescript-eslint/comma-dangle": 0,
    "@typescript-eslint/indent": 0,
    "@typescript-eslint/member-delimiter-style": 0,
    "@typescript-eslint/no-extra-parens": 0,
    "@typescript-eslint/object-curly-spacing": 0,
    "@typescript-eslint/quotes": 0,
    "@typescript-eslint/semi": 0,
    "@typescript-eslint/space-before-function-paren": 0,
    "comma-dangle": 0,
    "generator-star-spacing": 0,
    indent: 0,
    "jsx-quotes": 0,
    "object-curly-spacing": 0,
    "operator-linebreak": 0,
    quotes: 0,
    "react/jsx-indent": 0,
    semi: 0,
    "space-before-function-paren": 0,
    "unicorn/no-nested-ternary": 0,
    "yield-star-spacing": 0,
  },
  "prettier-tailwind": {
    "@stylistic/arrow-parens": 0,
    "@stylistic/indent": 0,
    "@stylistic/jsx-indent": 0,
    "@stylistic/jsx-one-expression-per-line": 0,
    "@stylistic/member-delimiter-style": 0,
    "@stylistic/multiline-ternary": 0,
    "@stylistic/operator-linebreak": 0,
    "@stylistic/quotes": 0,
    "@stylistic/semi": 0,
    "@typescript-eslint/comma-dangle": 0,
    "@typescript-eslint/indent": 0,
    "@typescript-eslint/member-delimiter-style": 0,
    "@typescript-eslint/no-extra-parens": 0,
    "@typescript-eslint/object-curly-spacing": 0,
    "@typescript-eslint/quotes": 0,
    "@typescript-eslint/semi": 0,
    "@typescript-eslint/space-before-function-paren": 0,
    "jsx-quotes": 0,
    "object-curly-spacing": 0,
    quotes: 0,
    "react/jsx-indent": 0,
    "unicorn/no-nested-ternary": 0,
  },
  regexp: {
    "unicorn/better-regex": 0,
  },
  rn: {
    "@typescript-eslint/comma-dangle": 0,
  },
  "shopify-core": {
    "@stylistic/object-curly-spacing": 0,
    "@stylistic/operator-linebreak": 0,
    "@stylistic/quote-props": 0,
    "@stylistic/semi": 0,
    "@typescript-eslint/comma-dangle": 0,
    "@typescript-eslint/object-curly-spacing": 0,
    "@typescript-eslint/semi": 0,
    "prettier/prettier": 0,
    "prettier-tailwind/prettier": 0,
  },
  "shopify-esnext": {
    "@stylistic/arrow-parens": 0,
    "@stylistic/object-curly-spacing": 0,
    "@stylistic/semi": 0,
    "prettier/prettier": 0,
    semi: 0,
  },
  "shopify-prettier": {
    "@stylistic/arrow-parens": 0,
    "@stylistic/brace-style": 0,
    "@stylistic/indent": 0,
    "@stylistic/indent-binary-ops": 0,
    "@stylistic/jsx-indent": 0,
    "@stylistic/jsx-one-expression-per-line": 0,
    "@stylistic/member-delimiter-style": 0,
    "@stylistic/multiline-ternary": 0,
    "@stylistic/operator-linebreak": 0,
    "@stylistic/quote-props": 0,
    "@stylistic/quotes": 0,
    "@stylistic/semi": 0,
    "@stylistic/yield-star-spacing": 0,
    "@typescript-eslint/comma-dangle": 0,
    "@typescript-eslint/indent": 0,
    "@typescript-eslint/member-delimiter-style": 0,
    "@typescript-eslint/no-extra-parens": 0,
    "@typescript-eslint/object-curly-spacing": 0,
    "@typescript-eslint/quotes": 0,
    "@typescript-eslint/semi": 0,
    "@typescript-eslint/space-before-function-paren": 0,
    "comma-dangle": 0,
    "generator-star-spacing": 0,
    indent: 0,
    "indent-legacy": 0,
    "jsx-quotes": 0,
    "object-curly-spacing": 0,
    "operator-linebreak": 0,
    quotes: 0,
    "react/jsx-indent": 0,
    semi: 0,
    "space-before-function-paren": 0,
    "unicorn/no-nested-ternary": 0,
    "yield-star-spacing": 0,
  },
  "shopify-react": {
    "prettier/prettier": 0,
    "prettier-tailwind/prettier": 0,
  },
  "shopify-ts": {
    "@stylistic/block-spacing": 0,
    "@stylistic/brace-style": 0,
    "@stylistic/member-delimiter-style": 0,
    "@stylistic/object-curly-spacing": 0,
    "@stylistic/semi": 0,
    "@typescript-eslint/block-spacing": 0,
    "prettier/prettier": 0,
    "prettier-tailwind/prettier": 0,
    "unicorn/no-nested-ternary": 0,
  },
  "sort-class": {
    "perfectionist/sort-classes": 0,
  },
  standard: {
    "@babel/object-curly-spacing": 0,
    "@babel/semi": 0,
    "@stylistic/comma-dangle": 0,
    "@stylistic/operator-linebreak": 0,
    "@stylistic/quote-props": 0,
    "@stylistic/space-before-function-paren": 0,
    "prettier/prettier": 0,
  },
  "standard-jsx": {
    "prettier/prettier": 0,
    "prettier-tailwind/prettier": 0,
  },
  "standard-ts": {
    "@stylistic/comma-dangle": 0,
    "@stylistic/space-before-function-paren": 0,
    "prettier/prettier": 0,
    "prettier-tailwind/prettier": 0,
  },
  stylistic: {
    "@babel/object-curly-spacing": 0,
    "@babel/semi": 0,
    "@typescript-eslint/brace-style": 0,
    "@typescript-eslint/comma-dangle": 0,
    "@typescript-eslint/member-delimiter-style": 0,
    "@typescript-eslint/object-curly-spacing": 0,
    "@typescript-eslint/semi": 0,
    "@typescript-eslint/space-before-function-paren": 0,
    "arrow-parens": 0,
    "block-spacing": 0,
    "brace-style": 0,
    "comma-dangle": 0,
    indent: 0,
    "object-curly-spacing": 0,
    "operator-linebreak": 0,
    "prettier/prettier": 0,
    "prettier-tailwind/prettier": 0,
    "quote-props": 0,
    semi: 0,
    "space-before-function-paren": 0,
  },
  unicorn: {
    "@typescript-eslint/no-extra-parens": 0,
    "prettier/prettier": 0,
    "prettier-tailwind/prettier": 0,
    "regexp/strict": 0,
  },
  xo: {
    "@stylistic/brace-style": 0,
    "@stylistic/indent": 0,
    "@stylistic/indent-binary-ops": 0,
    "@stylistic/object-curly-spacing": 0,
    "@stylistic/quote-props": 0,
    "@stylistic/semi": 0,
    "indent-legacy": 0,
    "prettier/prettier": 0,
  },
};

export default incompatibles;
// EOF
